version: 1
formatters:
    simple:
        style: '$'
        format: '$name - $levelname - $message'
    complex:
        style: '$'
        format: '$asctime - $levelname - $filename[$lineno] - $message'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    fileh:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: 'GncTxsFromMonarch.gncout'
        filters: [special]
filters:
    special:
        (): parseMonarchCopyRep.SpecialFilter
loggers:
    gnucash:
        level: DEBUG
        handlers: [console,fileh]
        propagate: no
root:
    level: INFO
    handlers: [console]
